name: Lint Helm charts

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches: [ main ]


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: stunner-helm checkout
        uses: actions/checkout@v4
        with:
          path: stunner-helm
          ref: main
          repository: l7mp/stunner-helm

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (lint)
        run: |
          cd stunner-helm
          ct lint --chart-dirs helm --charts helm/stunner-gateway-operator
